Style/TrailingCommaInHashLiteral:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - lib/project_types/script/messages/messages.rb
    - lib/project_types/script/ui/error_handler.rb
