Layout/FirstArgumentIndentation:
  Exclude:
    - lib/shopify-cli/tasks/ensure_dev_store.rb
Layout/HeredocIndentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - lib/project_types/script/messages/messages.rb
