inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify:
    - rubocop-cli.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'docs/**/*'
    - 'packaging/**/*'
  TargetRubyVersion: 2.4

Layout/EmptyLines:
  Exclude:
    # Need extra line so comment at top isnt registered to the Dev namespace
    - 'lib/dev/helpers/chruby_reset.rb'

# Changing this could effect the way the content is rendered.
Layout/HeredocIndentation:
  Exclude:
    - 'lib/project_types/node/messages/messages.rb'
    - 'lib/project_types/rails/messages/messages.rb'
    - 'lib/project_types/script/messages/messages.rb'
    - 'lib/shopify-cli/messages/messages.rb'

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow String.new to create mutable strings
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

# allow using %r{} for regexes
Style/RegexpLiteral:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - require
    - require_relative
    - require_dependency
    - yield
    - raise
    - puts
    - assert_equal
    - assert
    - refute
    - assert_requested # from Webmock
