inherit_from: .rubocop_todo.yml

require: rubocop-minitest

inherit_gem:
  rubocop-shopify:
    - rubocop-cli.yml

Minitest:
  Enabled: true
  Include:
    - '**/test/**/*'
    - '**/*_test.rb'

Minitest/AssertInDelta: # (new in 0.10)
  Enabled: true
Minitest/AssertionInLifecycleHook: # (new in 0.10)
  Enabled: true
Minitest/AssertKindOf: # (new in 0.10)
  Enabled: true
Minitest/AssertOutput: # (new in 0.10)
  Enabled: true
Minitest/AssertPathExists: # (new in 0.10)
  Enabled: false # only available from minitest 5.13.0
Minitest/AssertSilent: # (new in 0.10)
  Enabled: true
Minitest/LiteralAsActualArgument: # (new in 0.10)
  Enabled: true
Minitest/MultipleAssertions: # (new in 0.10)
  Enabled: true
Minitest/RefuteInDelta: # (new in 0.10)
  Enabled: true
Minitest/RefuteKindOf: # (new in 0.10)
  Enabled: true
Minitest/RefutePathExists: # (new in 0.10)
  Enabled: false # only available from minitest 5.13.0
Minitest/TestMethodName: # (new in 0.10)
  Enabled: true
Minitest/UnspecifiedException: # (new in 0.10)
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'docs/**/*'
    - 'packaging/**/*'
  TargetRubyVersion: 2.4

Layout/EmptyLines:
  Exclude:
    # Need extra line so comment at top isnt registered to the Dev namespace
    - 'lib/dev/helpers/chruby_reset.rb'

# Changing this could effect the way the content is rendered.
Layout/HeredocIndentation:
  Exclude:
    - 'lib/project_types/node/messages/messages.rb'
    - 'lib/project_types/rails/messages/messages.rb'
    - 'lib/project_types/script/messages/messages.rb'
    - 'lib/shopify-cli/messages/messages.rb'

# allow String.new to create mutable strings
Style/EmptyLiteral:
  Enabled: false

# allow String.new to create mutable strings
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

# allow using %r{} for regexes
Style/RegexpLiteral:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - require
    - require_relative
    - require_dependency
    - yield
    - raise
    - puts
    - assert_equal
    - assert
    - refute
    - assert_requested # from Webmock
