language: ruby
rvm:
 - 2.5.8
 - 2.6.6
 - 2.7.1
before_install:
- gem install bundler -v '1.17.3'
cache:
  bundler: true
install:
- bundle install
script:
  - bundle exec rake
  - if [ -f "~/.config/shopify/config" ]; then echo "Found a config file in home directory. This means the tests would modify a developer's local config. Consider using FakeFS"; exit 1; fi
