name: dev
type:
  - ruby

env:
  SHOPIFY_CLI_DEVELOPMENT: "1"

up:
  - ruby: 2.7.5
  - homebrew:
      - dpkg:
          version: 1.21.1
      - rpm:
          version: 4.17.0
  - bundler
  - docker

test:
  desc: "Run tests."
  run: |
    if [ "$#" -eq 1 ] && [[ -f $1 ]];
    then
      bundle exec rake test TEST=$1
    else
      bundle exec rake test $@
    fi

commands:
  style:
    run: bundle exec rubocop .
  typecheck:
    desc: 'run Sorbet typechecking'
    aliases: ['tc']
    depends-railgun: false
    run: bin/srb tc 
  rbi:
    desc:   "generate Ruby interface files for Sorbet"
    subcommands:
      gems:
        desc: "updates gem RBI files."
        run: bin/tapioca gem
      dsl:
        desc: "update RBI files for various DSLs. Use 'dev rbi dsl <fully-qualified-class-name, ...>' to update individual class RBI files."
        run: bin/tapioca dsl
