name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: preflight-checks
    attributes:
      label: Before jumping to submit...
      description: |-
        Hi! 👋 Thanks for taking the time to open an issue.

        **Before submitting your issue**, please confirm:
      options:
        - label: I've searched the [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if someone else has already submitted the same thing. (Feel free to add any additional information in a comment!)
          required: true
        - label: I've given as much detail as reasonably possible
          required: true
        - label: I've tested with the [latest CLI version](https://github.com/Shopify/shopify-cli/releases)
          required: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## General Questions'
  - type: dropdown
    id: app-type
    attributes:
      label: What type of project are you working on?
      options:
        - app
        - extension
        - script
        - theme
        - other
    validations:
      required: true
  - type: textarea
    id: issue-summary
    attributes:
      label: Issue summary
      description: Write a short description of the issue here ↓
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What do you think should have happened?
      placeholder: It should have worked
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: It didn't work
    validations:
      required: true
  - type: textarea
    id: stack-trace
    attributes:
      label: Stack trace
      description: Paste in a stack trace if you've got one!
      render: shell
    validations:
      required: false
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: Let us know the exact steps required to reproduce the error. The more detail, the better!
      value: |-
        1.
        2.
        3.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <hr/>

        ## Environment Details

        Just a few more technical questions, to help us understand if your bug is linked to a particular runtime enviroment.
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 11, Mac OS Monterey, Ubuntu 20.04...
    validations:
      required: true
  - type: input
    id: cli-version
    attributes:
      label: What CLI version are you running? (run `shopify version` if you're not sure)
      placeholder: 2.10.0
    validations:
      required: true
  - type: input
    id: shell
    attributes:
      label: Shell
      placeholder: Cygwin, Git Bash, iTerm2, bash, zsh...
  - type: input
    id: ruby-version
    attributes:
      label: What Ruby version are you running? (run `ruby -v` if you're not sure)
      placeholder: 3.0.2p107
  - type: input
    id: other-versions
    attributes:
      label: What language and version are you using in your application?
      placeholder: Ruby 3.0.3, Node 17.1, PHP 7.4...
