discount:
  assemblyscript:
    package: "@shopify/extension-point-as-discount"
    version: "~0.0.13"
    sdk-version: "^1.3.0"
unit_limit_per_order:
  assemblyscript:
    package: "@shopify/extension-point-as-unit-limit-per-order"
    version: "~0.0.13"
    sdk-version: "^1.3.0"
