name: CI

on: [push, pull_request]

jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: macos-latest
    strategy:
      matrix:
        version:
          - 3.0.0
          - 2.6.6
          - 2.7.1
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.version }}
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rake
