# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 3 * * *' # randomly chosen time of day

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 90
        days-before-pr-stale: 30
        days-before-close: 10
        stale-issue-message: |-
          This issue seems inactive. If it's still relevant, please add a comment saying so. Otherwise, take no action.

          → If there's no activity within a week, then a bot will automatically close this.

          Thanks for helping to improve Shopify's dev tooling and experience.
        stale-pr-message: |-
          This PR seems inactive. If it's still relevant, please add a comment saying so. Otherwise, take no action.

          → If there's no activity within a week, then a bot will automatically close this.

          Thanks for helping to improve Shopify's dev tooling and experience.
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        operations-per-run: 30 # Should allow for 10 issues per run
