name: Triage new issues to DTE oncall project board ("Needs triage" column)

on:
  issues:
    types: [opened, reopened]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Extract issue id
      id: issue
      run: echo "::set-output name=id::$(jq -r '.issue.id' < "$GITHUB_EVENT_PATH")"

    - name: Create card
      env:
        TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        curl -s -X POST -u "$GITHUB_ACTOR:$TOKEN" --retry 3 \
          -H 'Accept: application/vnd.github.inertia-preview+json' \
          -d "{\"content_type\": \"Issue\", \"content_id\": ${{ steps.issue.outputs.id }}}" \
          "https://api.github.com/projects/columns/10507989/cards"
